
const CardConstants = ({
  ADD_TO_CARD: 'ADD_TO_CARD',
  GET_TO_CARD: 'GET_TO_CARD',
  DELETE_TO_CARD: 'DELETE_TO_CARD',
  DELETE_TO_CARDS: 'DELETE_TO_CARDS',
  SUBTRACT_TO_CARDS: 'SUBTRACT_TO_CARDS'
})


export default CardConstants;