
const CardConstants = ({
  ADD_TO_CARD: 'ADD_TO_CARD',
  GET_TO_CARD: 'GET_TO_CARD',
  DELETE_TO_CARD: 'DELETE_TO_CARD',
  DELETE_TO_CARDS: 'DELETE_TO_CARDS',
  SUBTRACT_TO_CARDS: 'SUBTRACT_TO_CARDS',
  SET_CHECKED: 'SET_CHECKED',
  INCREASE_ORDER_COUNT: 'INCREASE_ORDER_COUNT',
  DECREASE_ORDER_COUNT: 'DECREASE_ORDER_COUNT',
  REMOVE_ORDER_TO_CARD: 'REMOVE_ORDER_TO_CARD',

})


export default CardConstants;